platform :ios, '7.0'
def testing_pods
    pod 'AFNetworking', '~> 3.0’
    pod 'SDWebImage', '~> 3.7.5'
    pod 'MJExtension', '~> 3.0.10'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'YYWebImage'
    pod 'YLGIFImage'
    pod 'Qiniu', '~> 7.1’
    pod 'Masonry'
    pod 'OpenSSL-Universal', '~> 1.0.1.18'
    pod 'YYText'
    pod 'ShareSDK3'
    pod 'MOBFoundation'
    pod 'ShareSDK3/ShareSDKPlatforms/QQ'
    pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
    pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
    pod 'UMengAnalytics-NO-IDFA'
    pod 'YYImage/WebP'
    pod 'SSZipArchive'
    pod 'RegExCategories', '~> 1.0'
    pod 'QBPopupMenu', '~> 2.0'
end

target ‘MaxMineCraft’ do
    testing_pods
end
